# DjiNN and Tonic Makefile.config
# Set Caffe path
# (be sure to run make distribute as the final step in Caffe)
CAFFE=../caffe-1.0/distribute

# Cuda path
CUDA=/usr/local/cuda

# CPU-only switch (uncomment to build without GPU support)
# Caffe must be built
#CPU_ONLY := 1

# other directories to search
INCLUDE_DIRS := -I/usr/local/include -I/usr/include/hdf5/serial/ -I/usr/local/cuda/include


#TITAN X
#LIBRARY_DIRS := -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial/ -L/usr/local/cuda/lib64 -L/usr/lib/nvidia-384

#P100
#LIBRARY_DIRS := -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/hdf5/serial/ -L/usr/local/cuda/lib64 -L/usr/lib/nvidia-375
